## Define stages and order of execution

stages:
  - WATCH-BUILD

WATCHER:
  image: atulabhi/kops:v8
  stage: WATCH-BUILD
  script:
    - chmod 755 ./watcher.sh
    - ./watcher.sh $CI_PROJECT_NAME $CI_COMMIT_REF_NAME $USERNAME $PASSWORD
