## Define stages and order of execution

stages:
  - WATCH-BUILD
  - BASELINE
WATCHER:
  image: atulabhi/kops:v8
  stage: WATCH-BUILD
  script:
    - chmod 755 ./watcher.sh
    - ./watcher.sh $CI_PROJECT_NAME $CI_COMMIT_REF_NAME $USERNAME $PASSWORD
BASELINE-IMAGE:
  stage: BASELINE
  only:
    - staging-mo-grafana
  image: atulabhi/kops:v8
  dependencies:
     - WATCHER
  script:
     - echo "###############################################################################################"
     - curl -X POST -F token=$GCP -F ref=$REF_NAME https://gitlab.mayadata.io/api/v4/projects/5/trigger/pipeline
